### ISSUE TITLE
User Idea Card Creation

### ISSUE THREAD

**Issue by jobannon** [jobannon/upvote_ui#4]
```
As an authenticated user
When I visit the dashboard
And click a link/button to add an idea card
I am then redirected to './ideas/new'
Where I see a form
And when I fill in project title (required)
And I fill in pitch (required)
And I fill in problem (required)
And I fill in solution (required)
And I fill in the audience (required)
And I fill in features (required)
And I fill in integration (required)
And I click submit
Then I should be redirected to the dashboard
And I should see a message that says "Your Idea Has Been Submitted"
And I should see my idea depicted as a card on the dashboard,
Containing the project title and a background image
```
- [ ] Sad path accounted for (if the form is not filled in completely)
- [x] API call to retrieve background image
- [x] User–Ideas one-to-many relationship

**Tasks**
- [x] Create Idea table with columns: title, pitch, problem, solution, audience, features, integration, user_id (foreign key) 
- [x] Create view
- [x] Create Idea model
- [x] Create Idea controller

### Idea CRUD Page ![idea CUD page](https://user-images.githubusercontent.com/50811220/74800101-adecce00-528f-11ea-91a8-65896c4325dc.png)
